spring:
  application:
    name: 'msp-evolution-core'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  cloud:
    stream:
      bindings:
        input:
          destination: 'EventFeed'
        output:
          destination: 'EventStateFeed'
#        input2:
#          destination: 'EventStateFeed'