#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000

spring:
  application:
    name: 'msp-evolution.core'
  kafka:
    bootstrap-servers: 'localhost:9092'
server:
  port: 8787