spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000


spring:
  application:
    name: 'evolution-msp-user'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  data:
    rest:
      base-path: '/state'
  cloud:
    stream:
      bindings:
        input:
          destination: UserStateFeed
server:
  port: 8381