spring.kafka.consumer.properties.spring.json.trusted.packages: 'com.evolution.*'


spring:
  application:
    name: 'evolution-user'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: 'com.evolution.*'
  cloud:
    stream:
      bindings:
        input:
          destination: UserStateFeed
        input-command-status:
          destination: AbstractCommandFeed
  data:
    rest:
      base-path: '/state'
server:
  port: 8181
