spring:
  application:
    name: 'msp-evolution-user'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  cloud:
    stream:
      bindings:
        command-input:
          destination: UserCommandFeed
        command-output:
          destination: UserEventFeed
        event-input:
          destination: UserEventFeed
        event-output:
          destination: UserStateEventFeed
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 100
              default.key.serde: 'org.apache.kafka.common.serialization.Serdes$StringSerde'
              default.value.serde: 'org.springframework.kafka.support.serializer.JsonSerde'
            application-id: 'msp-evolution-user'
  data:
    rest:
      base-path: '/state'
server:
  port: 8181