spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000

spring:
  application:
    name: 'evolution-user'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  cloud:
    stream:
      bindings:
        input-create-user:
          destination: UserCreateEventFeed
        input-update-user:
          destination: UserUpdateEventFeed
        output-state-user:
          destination: UserStateEventFeed
        input:
          destination: UserStateEventFeed
      kafka:
        streams:
          binder:
            applicationId: 'evolution-user-1'
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
  data:
    rest:
      base-path: '/state'
server:
  port: 8381