spring:
  application:
    name: 'evolution-direct-message-processor'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  cloud:
    stream:
      bindings:
#       MessageStateKProcessor
        input-message-create:
          destination: MessageCreateEventTopic
        input-message-update-text:
          destination: MessageUpdateTextEventTopic
        output-message-state:
          destination: MessageStateEventTopic
#       MessageStateKProcessor
#       MessageDerormalizationStateKProcessor
        input-message-state:
          destination: MessageStateEventTopic
        input-user-state:
          destination: UserStateEventTopic
        output-message-denormalization-state:
          destination: MessageDenormalizationStateEventTopic
#       MessageDerormalizationStateKProcessor
      kafka:
        streams:
          binder:
            applicationId: 'evolution-direct-message-processor'
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
server:
  port: 8281