#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000

spring:
  application:
    name: 'evolution-direct-message-processor'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
      group-id: 'evolution-direct-message-processor'
  cloud:
    stream:
      bindings:
        input-create:
          destination: CreateMessageEventTopic
          contentType: application/json
        input-update:
          destination: UpdateTextMessageEventTopic
          contentType: application/json
        output-result:
          destination: MessageStateEventTopic
          contentType: application/json
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
server:
  port: 8481