spring:
  application:
    name: 'msp-evolution-direct-message-query'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  data:
    rest:
      base-path: '/state'
  cloud:
    stream:
      bindings:
        input:
          destination: MessageDenormalizationStateFeed
server:
  port: 8282