#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kstream.binder.configuration.application.id: 'testttt'

spring:
  application:
    name: 'evolution-direct-message'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
  data:
    rest:
      base-path: '/state'
  cloud:
    stream:
      bindings:
        input-message-state:
          destination: MessageStateEventTopic
        input-message-state-denormalizate:
          destination: MessageDenormalizationStateEventTopic
      kafka:
        streams:
          binder:
#            applicationId: 'evolution-direct-message'
            configuration:
                default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
server:
  port: 8181