spring:
  application:
    name: 'evolution-user-processor'
  kafka:
    bootstrap-servers: 'localhost:9092'
  cloud:
    stream:
      bindings:
        input-create:
          destination: UserCreateEventTopic
        input-update:
          destination: UserUpdateEventTopic
        output-result-state:
          destination: UserStateEventTopic
      kafka:
        binder:
          configuration:
            commit.interval.ms: 1000
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
server:
  port: 8481